### ISSUE TITLE
Waiting for animation to finish not finished

### ISSUE THREAD

**Issue by hamoid** [openrndr/openrndr-guide#20]
https://github.com/openrndr/openrndr-guide/blob/master/docs/08_Animation/C00_InteractiveAnimations.md#waiting-for-an-animation-to-finish

The last two code boxes seem incomplete.

**Comment by edwinRNDR** [comment]
@krksgbr this is a `dokgen` issue ```  @Code
            myAnimatable.apply {
                animate("x", 400.0, 2000)
                animate("y", 500.0, 1200)
                complete("x")
            }

**Comment by edwinRNDR** [comment]
Fixed and live!
