### ISSUE TITLE
Missing ':run' in explanation howto run tutorials?

### ISSUE THREAD

**Issue by xabbu137** [openrndr/openrndr-guide#25]
Hi - I think there is a ':run' missing in the last sentence of

https://guide.openrndr.org/#/02_Getting_Started_with_OPENRNDR/C01_TutorialRepository?id=running-tutorials-from-the-command-line

`You can run an individual example from the tutorial repository from the command line using ./gradlew :<project-name>` → `You can run an individual example from the tutorial repository from the command line using ./gradlew :<project-name>:run`

At least for me this is required to actually run a tutorial.

**Comment by hamoid** [comment]
This issue became outdated (the link is not working) but it's still relevant: how to run the examples from the command line?

Now thanks to this it should be possible: https://github.com/openrndr/openrndr-template#run-other-kotlin-programs-from-the-command-line

I will do two things to make it work:

- [ ] Update the Template used in the examples to the last version, so we can use `-Popenrndr.application=foo.bar.MyProgramKt`
- [ ] Update the readme.md in the examples to explain how to use this feature.

**Comment by hamoid** [comment]
I just noticed you were actually referring to the Tutorials repository, which is now abandoned.

Most of the examples can now be found in the [guide](https://guide.openrndr.org/) and are automatically extracted into the [examples repository](https://github.com/openrndr/openrndr-examples).

I added a note explaining [how to run those examples from the command line](https://github.com/openrndr/openrndr-examples#usage).
