### ISSUE TITLE
Wrong index in example in C00_Render_targets_and_color_buffers

### ISSUE THREAD

**Issue by xabbu137** [openrndr/openrndr-guide#26]
The example in 

https://guide.openrndr.org/#/06_Advanced_drawing/C00_Render_targets_and_color_buffers?id=compositing-using-render-targets-and-alpha-channels

gives an error, as `rt1` only has one colorbuffer, ie the code line

```drawer.image(rt1.colorBuffer(1))```

should be

```drawer.image(rt1.colorBuffer(0))```

instead imho.

**Comment by edwinRNDR** [comment]
Hi @xabbu137, that's correct! I have fixed the example.
