### ISSUE TITLE
add documentation for ColorBuffer.shadow

### ISSUE THREAD

**Issue by ylegall** [openrndr/openrndr-guide#31]
Add documentation for getting pixel color values using the [shadow property](https://api.openrndr.org/org.openrndr.draw/-color-buffer/shadow.html).

For example: https://openrndr.discourse.group/t/load-image-and-get-pixel-value/42

**Comment by edwinRNDR** [comment]
Indeed, the moving things in and out of ColorBuffer is heavily underlit in the documentation.
