### ISSUE TITLE
Writing SVG Files is missing

### ISSUE THREAD

**Issue by sbauer322** [openrndr/openrndr-guide#35]
At the bottom of the [Drawing SVG](https://guide.openrndr.org/#/04_Drawing_basics/C06_DrawingSvg) chapter there is a link for how to write SVG files, however, the link goes to a [blank page](https://guide.openrndr.org/#/Topic_WritingSVGFiles).

Is it that the link is incorrect or that the content doesn't exist yet?

**Comment by edwinRNDR** [comment]
Hi @sbauer322, looks like it was imported from an older version of the documentation. Link is incorrect and I can't find the original content anymore. I have updated the page, it should be live in 10 minutes.

**Comment by sbauer322** [comment]
Awesome, thank you!
