### ISSUE TITLE
ShadeStyles missing some information

### ISSUE THREAD

**Issue by ricardomatias** [openrndr/openrndr-guide#37]
[Link](https://guide.openrndr.org/advancedDrawing/shadeStyles.html)

Does not mention:
* x_modelMatrix
* x_modelNormalMatrix

Perhaps there could be some examples which make use of one of the preprocessors and vertexTransform.

**Comment by hamoid** [comment]
More issues based on https://github.com/openrndr/openrndr/blob/master/openrndr-gl3/src/main/kotlin/org/openrndr/internal/gl3/ShaderGeneratorsGL3.kt

* u_viewMatrix is repeated. remove first one?
* va_position remove?
* va_normal remove?
* va_texCoord0 add?
* x_modelMatrix = u_modelMatrix; add?
* x_modelNormalMatrix = u_modelNormalMatrix; add?
* x_viewMatrix remove?
* x_viewNormalMatrix = u_viewNormalMatrix; add?
* c_boundsPosition add?
* c_boundsSize add?

Also missing:
* v_worldNormal;
* v_viewNormal;
* v_worldPosition;
* v_viewPosition;
* v_clipPosition;
* v_modelNormalMatrix;

Shouldn't these be all `va_` instead? They are varyings.

Also, if it's likely to be out-of-date maybe there could be a link to https://github.com/openrndr/openrndr/blob/master/openrndr-gl3/src/main/kotlin/org/openrndr/internal/gl3/ShaderGeneratorsGL3.kt where one can check the true thing :)
