### ISSUE TITLE
Fonts not found

### ISSUE THREAD

**Issue by holgerbrandl** [openrndr/openrndr-guide#53]
When trying to draw some text as explained in https://guide.openrndr.org/#/04_Drawing_basics/C02_Text using the current master of https://github.com/openrndr/openrndr-template with 

```
fun main() = application {
    configure {
        width = 800
        height = 800
    }
    program  {
        val font = loadFont("file:data/IBMPlexMono-Bold.ttf", 24.0)

        extend {
            drawer.fontMap = font
            drawer.fill = ColorRGBa.WHITE
            drawer.text("Counter $seconds", width / 2.0 - 100.0, height / 2.0)
        }
    }
}
```

it fails with 
```
Exception in thread "main" java.io.FileNotFoundException: data\IBMPlexMono-Bold.ttf (The system cannot find the file specified)
```

It would be great if example-template (or one of the dependencies) could either somehow include these fonts, or the doc-example would use a default system font.

I managed to solve the issue by downloading the fonts from https://fonts.google.com/specimen/IBM+Plex+Mono

**Comment by hamoid** [comment]
I think now there's a default font, so if you remove the two lines mentioning "font" you should still see text rendered (at least it works for me). This could be also mentioned in the guide :-)

**Comment by hamoid** [comment]
I fixed it by making sure both the template and the guide use the same default font location. The change will be there with the next version of the guide.

**Comment by hamoid** [comment]
The examples from the guide https://guide.openrndr.org/drawingBasics/text.html now use a font that is available in the [template](https://github.com/openrndr/openrndr-template/tree/master/data/fonts) and in the [examples](https://github.com/openrndr/openrndr-examples/tree/master/data/fonts).
