### ISSUE TITLE
Invalid full example links in guide

### ISSUE THREAD

**Issue by holgerbrandl** [openrndr/openrndr-guide#66]
The links to the full examples on https://guide.openrndr.org/#/10_OPENRNDR_Extras/C01_Noise are all 404

**Comment by hamoid** [comment]
It seems examples were deleted in the last commit: https://github.com/openrndr/openrndr-examples/commit/b4c834987093365c0d4755f447087c2d89967573 (unintentionally?)

**Comment by hamoid** [comment]
Until it is fixed you can find them at https://github.com/openrndr/openrndr-examples/tree/6ce2c53e2b93b5c88a7e8f005a12cf205f3f65c5/src/main/kotlin/examples

**Comment by hamoid** [comment]
This is now fixed
