### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by 12people** [openrndr/openrndr-guide#67]
There are a number of dead links floating around online to pages in the guide that are no longer there.

For example, the Tutorials link on the [OpenRNDR homepage](https://openrndr.org/) itself is dead. So are old links in Github issues (e.g. [this issue](https://github.com/openrndr/openrndr/issues/12#issuecomment-405487685)).

It'd be great if the guide automatically redirected from the old links to the new links. Alternatively, it could at least show search results for missing pages based on the slug.

**Comment by edwinRNDR** [comment]
Fair points but I am afraid we don't really have tooling and process to keep track of old links inside the guide. 

Will look into what is up with the tutorial links on the homepage at least.

**Comment by hamoid** [comment]
I corrected the link in the issue. The link to Tutorials is still not working.

**Comment by hamoid** [comment]
There is an action to automate this:
https://github.com/marketplace/actions/lychee-broken-link-checker

**Comment by hamoid** [comment]
I added an action to check that links work:

https://github.com/openrndr/openrndr-guide/blob/main/.github/workflows/links.yml
