### ISSUE TITLE
Is there a way to write a png file for every frame?

### ISSUE THREAD

**Issue by mkpazon** [openrndr/openrndr-guide#88]
I'd like to create a PNG file for each frame within the extend {} block until it reaches a certain number of frames.

I tried using the Screenshots extension but I find it a bit hard to control. I am looking for something similar to the VideoWriter that works within the extend draw loop block but for pngs.

**Comment by hamoid** [comment]
Hi! Would the `PNGProfile` work for you?

https://github.com/openrndr/orx/tree/master/orx-jvm/orx-video-profiles

**Comment by mkpazon** [comment]
Thanks, that did help me.
